# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='blendmodes',
    version='2020.2.1',
    description='Use this module to apply a number of blending modes to a background and foreground image',
    python_requires='==3.*,>=3.6.0',
    project_urls={
        "documentation":
            "https://github.com/FHPythonUtils/BlendModes/blob/master/README.md",
        "homepage":
            "https://github.com/FHPythonUtils/BlendModes",
        "repository":
            "https://github.com/FHPythonUtils/BlendModes"
    },
    author='FredHappyface',
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Intended Audience :: Developers', 'Intended Audience :: Education',
        'License :: OSI Approved :: MIT License', 'Natural Language :: English',
        'Operating System :: OS Independent',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: Implementation :: CPython',
        'Topic :: Multimedia :: Graphics',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Topic :: Utilities'
    ],
    packages=['BlendModes'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'numpy==1.*,>=1.18.3', 'pillow==7.*,>=7.1.2',
        'scikit-image==0.*,>=0.16.2'
    ],
    extras_require={"dev": ["imgcompare==2.*,>=2.0.1"]},
)
